<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Aspire.Hosting.Ollama" Version="13.1.2-beta.518" />
    <PackageVersion Include="CommunityToolkit.Aspire.OllamaSharp" Version="13.1.2-beta.518" />
    <PackageVersion Include="Microsoft.Agents.AI" Version="1.0.0-rc2" />
    <PackageVersion Include="Microsoft.Agents.AI.DevUI" Version="1.0.0-preview.260225.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Hosting" Version="1.0.0-preview.260225.1" />
    <PackageVersion Include="Microsoft.Agents.AI.Hosting.OpenAI" Version="1.0.0-alpha.260225.1" />
    <PackageVersion Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-rc2" />
    <PackageVersion Include="Microsoft.Agents.AI.Workflows" Version="1.0.0-rc2" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
    <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.3.0" />
    <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.3.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageVersion Include="ModelContextProtocol" Version="1.0.0" />
    <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.15.0" />
    <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.15.0" />
  </ItemGroup>
</Project>