<Project Sdk="Aspire.AppHost.Sdk/13.1.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>e9789e79-129d-4802-82cf-71931d9466fe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Orleans" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\samples\Samples\Samples.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" IsAspireProjectResource="false" />
    <ProjectReference Include="..\DevUI\DevUI.csproj" />
    <ProjectReference Include="..\Clients.Telegram.Bot\TelegramBot.csproj" />
  </ItemGroup>

</Project>
