<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>TelegramClient</RootNamespace>
    <NoWarn>$(NoWarn);NU1603</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <PackageReference Include="Microsoft.Orleans.Streaming" />
    <PackageReference Include="Telegram.BotAPI" />
    <PackageReference Include="Concentus" />
    <PackageReference Include="Concentus.Oggfile" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="OpenAI" />
    <PackageReference Include="Aspire.Azure.Storage.Blobs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Agents\Agents.csproj" />
    <ProjectReference Include="..\IAW.ServiceDefaults\ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
